services:
  padel-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CARGO_BUILD_FLAGS=${CARGO_BUILD_FLAGS:-}
    image: viva-padel-server:latest
    container_name: viva-padel-server
    ports:
      - "3000:3000"
    env_file:
      - ${DATA_PATH:-./server}/.env
    volumes:
      # Mount database for persistent data
      - ${DATA_PATH:-./server/data}:/usr/local/share/viva-padel-server/data
      # Mount mock data for testing
      - ./crates/testcases/data:/usr/local/share/viva-padel-server/mock-data
    environment:
      - DATABASE_URL=sqlite:///usr/local/share/viva-padel-server/data/viva_padel.db?mode=rwc
      - LOG_DIRECTORY=/usr/local/share/viva-padel-server/data/logs
      - PADEL_MOCK_DATA=/usr/local/share/viva-padel-server/mock-data
    entrypoint: ["viva-padel-server"]
    # entrypoint: ["/bin/sh", "-c", "viva-padel-server || tail -f /dev/null"]
    restart: always
  padel-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - EXPO_PUBLIC_API_URL=${EXPO_PUBLIC_API_URL:-http://localhost:3000/viva-padel}
        # take value from env or default test value
        - EXPO_PUBLIC_VAPID_PUBLIC_KEY=${EXPO_PUBLIC_VAPID_PUBLIC_KEY:- BPxwXQ-MQXONA6m3UHVk3G29hsx_G0Z7ufl0xZ5yK5qY_q2HSfwbvXSipwdksgthcGtCeJeM3a9OU8kF0VHskaM}
    image: viva-padel-client:client
    container_name: viva-padel-client
    ports:
      - "3001:80"
    depends_on:
      - padel-server
    # entrypoint: ["viva-padel-server"]
    restart: always
